### ISSUE TITLE
entityToHTML doesn't work for element like "img"

### ISSUE THREAD

**Issue by vangavroche** [HubSpot/draft-convert#101]
Assuming I have such an entityToHTML
```
      entityToHTML: (entity, originalText) => {
        if(entity.type === "IMAGE") {
          return (
             <img src={entity.data.src} style={{width: "100%"}}/>
          )
        }
      }
```

It goes to the https://github.com/HubSpot/draft-convert/blob/master/src/blockEntities.js#L34 to get tag element length:
```
      const entityHTML = getEntityHTML(entity, originalText);
      const converted = [...getElementHTML(entityHTML, originalText)
                        || originalText];

      const prefixLength = getElementTagLength(entityHTML, 'start');
      const suffixLength = getElementTagLength(entityHTML, 'end');

```

The getElementTagLength (https://github.com/HubSpot/draft-convert/blob/master/src/util/getElementTagLength.js#L6) use splitReactElement:
```
const getElementTagLength = (element, type = 'start') => {
  if (React.isValidElement(element)) {
    const length = splitReactElement(element)[type].length;

    const child = React.Children.toArray(element.props.children)[0];
    return length + (child && React.isValidElement(child)
      ? getElementTagLength(child, type)
      : 0
    );
  }
  ......
```

However the splitReactElement than treat the <img> as "void element" (https://github.com/HubSpot/draft-convert/blob/master/src/util/splitReactElement.js#L25) , where it directly returns a String, rather than `{start: <sth>, end: <sth>}`:
```
if (VOID_TAGS.indexOf(element.type) !== -1) {
    return ReactDOMServer.renderToStaticMarkup(element);
  }

```

Then the `splitReactElement(element)[type].length` report an error.

Isn't it an issue, or am I missing something?

**Comment by Discordius** [comment]
I am running into the same issue. Help would be appreciated.

**Comment by JohnMaguir** [comment]
Same issue, entity to void tags such as `img` will throw errors

**Comment by Pranab16** [comment]
I am facing the same error. @benbriggs

**Comment by JohnMaguir** [comment]
A quick workaround for this is to use a string instead of a React DOM element.
So instead of the React.DOM img element use "<img src='...' />" within the entityToHTML method.
Not sure why this works but was a quick fix for me until the actual issue is fixed.

**Comment by benbriggs** [comment]
just opened #111 with a fix that seems to work - it'd be great to get verification from you guys trying it out. sorry for the wait!
