### ISSUE TITLE
updated peerDependencies - React v16

### ISSUE THREAD

**Issue by oskarwalker** [HubSpot/draft-convert#108]
Can we expect updated `peerDependencies` for the draft-convert project in the near future?

I'am specifically thinking of the `react` and `react-dom` packages which are both locked to `^15.0.2`. If you can see that the upgrade is working fine, maybe you can change the `peerDependencies` to something like `^15.0.2 || ^16.0`.

At the moment, we can not upgrade to React v16 due to the locked version.

**Comment by benbriggs** [comment]
published in 2.0.1 via #106, sorry for the wait!
