### ISSUE TITLE
Multiple emoji followed by a styled apostrophe or quote render HTML entity

### ISSUE THREAD

**Issue by kaylee42** [HubSpot/draft-convert#117]
I've found a strange bug where if there are multiple emoji in a single block and they are followed by an apostrophe or quote which has an inline style, the HTML entity for the apostrophe/quote is split by the styling tag (ie `<strong>`). This results in text which should be rendered like this: 
aaa😥😥**a'a**a

rendering like this (okay apparently this makes markdown sad but you can imagine that the * rendered as bold): 
aaa😥😥**a&#**x27;aa

I haven't had time to dig into this but I did write tests on to demonstrate this bug on [this branch](https://github.com/kaylee42/draft-convert/tree/emoji-test). My initial thought was that it was being caused by something in `blockInlineStyles`, but as you see if you run the (nearly identical) tests, the one for just `blockInlineStyles` passes but the test on `convertToHTML` fails.

**Comment by benbriggs** [comment]
testing this locally i think https://github.com/HubSpot/draft-convert/pull/102 will solve this! hoping to merge it soon.

**Comment by benbriggs** [comment]
should be fixed in 2.1.2
