### ISSUE TITLE
atomic blocks convertToHTML: Cannot read property 'nest' of undefined

### ISSUE THREAD

**Issue by RobrechtM** [HubSpot/draft-convert#129]
First of all, this is a really good package! Super clean and easy to use.  
I have trouble converting custom **atomic blocks** to HTML. I use atomic blocks for media, iframes and tables, with their data stored in entities. I wrote a custom `entityToHTML` which handles the conversion. When I try to convert an editorState containing an atomic block linked to an entity to HTML, I get this error:  
`Cannot read property 'nest' of undefined: .../draft-convert/lib/convertToHTML.js:89`.
The problem seems to be in [this](https://github.com/HubSpot/draft-convert/blob/62da01096c035594026b1b7de1906deb5302c581/src/convertToHTML.js#L53) line.

However, when I manually change the blocktype from `atomic` to `unstyled`, it renders my entity perfecly.  
I still want to use the `atomic` block functionnality, so changing the type is no option. 
Any suggestion to what the problem can be?

<details>
  <summary>My code</summary>
<p>

```javascript
export const editorStateToHtml = editorState => {
  return convertToHTML({
    entityToHTML: (entity, originalText) => {
      if (entity.type === 'IFRAME') {
        const { data } = entity;
        const { width, height, src, title, alt, style } = data;
        return <iframe src={src} alt={alt} width={width} height={height} title={title || 'Embedded content'} frameBorder="0" style={style} />;
      } else if (entity.type === 'IMG') {
        const { data } = entity;
        const { width, height, src, alt, style } = data;
        return <img src={src} alt={alt} width={width} height={height} style={style} />;
      } else if (entity.type === 'VIDEO') {
        const { data } = entity;
        const { width, height, src, alt, style } = data;
        return <video src={src} alt={alt} width={width} height={height} style={style} />;
      } else if (entity.type === 'TABLE') {
        return (
          <table>
            <tbody>
              { entity.data.content.map(row => {
                return (
                  <tr>
                    {row.map(cell => (
                      <td>{cell}</td>
                    ))}
                  </tr>
              );
              })}
            </tbody>
          </table>
        );
      }
      return originalText;
    },
  })(editorState.getCurrentContent());
};
```

</p>
</details>

**Comment by benbriggs** [comment]
I think you're missing a `blockToHTML` definition for `atomic` blocks, which could be a `<figure />` tag (or whatever you want, really). As an aside I'd suggest using block metadata added in newer versions of Draft instead of an entity when building atomic blocks.

**Comment by RobrechtM** [comment]
Thanks for your quick and clear answer! Works like a charm now. I'll look into the block metadata, thanks for the tip.
