### ISSUE TITLE
How I can get draft-convert.js

### ISSUE THREAD

**Issue by m-pasha** [HubSpot/draft-convert#148]
I use in my project simple templates and need include  _draft-convert.js_ file. How I can build or download `draft-convert.js` file ??

**Comment by andrewmclagan** [comment]
Github is not a place to learn how to code - that is stackoverflow etc..

This is an *issue board* on an open source project. We use this to collaborate and work on improving the library.

**Comment by TrySound** [comment]
https://unpkg.com/browse/draft-convert@2.1.8/dist/
