### ISSUE TITLE
Support React elements

### ISSUE THREAD

**Issue by vinhlh** [HubSpot/draft-convert#15]
It will be great if supporting React elements, so we can define a parser like
```
const renderMention = (entity) => {
  const { id, username, name } = entity.data.mention
  return (  
    <Link to={`/user/${id}/${username}`}>
      {name}
    </Link>
  )
}
```

**Comment by benbriggs** [comment]
This is definitely interested in supporting and possibly making a default. It opens up the door for a better experience when building plugins that want to transform specific parts of a result. the one we've run into is when building out a feature to align blocks left/right/center, that plugin should be able to defer to all other plugins to define what element should have a `text-align` style tacked onto it. I'm ironing out the specifics of how I'd like to implement this but it should be coming soon in some form.
