### ISSUE TITLE
Allow manipulation of innerHTML

### ISSUE THREAD

**Issue by fix-me** [HubSpot/draft-convert#154]
Sometimes we have entities bound to a single whitespace character (e.g. " ") which we would like to remove or replace (for instance with some entity data property inside entityToHTML) in the exported html.
Maybe it works for a React component, but not for the {start, end, empty?} object, that only allows to export custom (non JSX.IntrinsicElements) markup.

I would suggest to extend the {start, end, empty?} tag-object with something like
**{start, end, empty?, innerHTML?}**
If innerHTML is empty originalText would be it by default.
Additionally provide a way to control the procession of rendering the children recursively (maybe by callback)

**Example:**
This could be useful for images or video entities for instance which are bound to " " inside an atomic block. I would like to export them as
```
{ 
  start: `<video width="${entity.data.width}" >`
  end: '</video>',
  innerHTML: `${entity.data.url}`
}
```

**Example 2 (nested stuff):**
The second example shows some spoiler entities which could contain nested elements, what would afford innerHTML to be Tag or have a callback function provided to process children.
Maybe innerHTML: (processChildren: Function) => string
```
{ 
  start: `<spoiler title="{entity.data.title}">`
  end: '</spoiler>',
  innerHTML: processChildren(originalText)
}
```

**Comment by benbriggs** [comment]
for your first example, you should be able to achieve this today by either returning just an HTML string instead of the object (or JSX, but you mentioned you didn't want to use it) representing the HTML `entityToHTML`.

e.g.
```
// in your entityToHTML definition
if (entity.type === 'video') {
  return `<video width="${entity.data.width}" >${entity.data.url}</video>`;
}
```

for the second example i believe just having the `{ start, end }` object as it stands today will allow for processing the contents of the entity range as you describe.
