### ISSUE TITLE
convertToHTML throws for "code-block"

### ISSUE THREAD

**Issue by pwlmaciejewski** [HubSpot/draft-convert#182]
### Description

`convertToHTML` throws `convertToHTML: missing HTML definition for block with type code-block` error when `ContentState` block type is `code-block`.

It's a confusing behavior given that `convertFromHTML` will convert `<pre>` tags to `code-blocks` from the HTML input: https://github.com/HubSpot/draft-convert/blob/master/src/convertFromHTML.js#L185

### Steps to reproduce

```jsx
convertToHTML(convertFromHTML("<pre>Foo</pre>"))
```
Demo: https://codesandbox.io/s/draft-convert-missing-html-definition-for-block-with-type-code-block-54nt4?file=/src/App.js

### Notes

Adding `'code-block': <pre />` to the default blocks (https://github.com/HubSpot/draft-convert/blob/master/src/default/defaultBlockHTML.js#L6) should fix the issue.

**Comment by MudulOzan** [comment]
Issue still exists

**Comment by benbriggs** [comment]
fixed in 2.1.12, sorry for the delay!

**Comment by Gtes** [comment]
Got the same problem while trying to use 2.1.12 with **react-draft-wysiwyg** 

Demo
https://codesandbox.io/s/crimson-sun-fle8vr?file=/src/App.js

**Comment by khalilabid95** [comment]
Got the same problem using "draft-convert": "^2.1.13"
