### ISSUE TITLE
peerDependencies to support React v18

### ISSUE THREAD

**Issue by uditalias** [HubSpot/draft-convert#212]
Can we expect updated peerDependencies for the draft-convert project in the near future?

At the moment, we can not upgrade to React v18 due to the locked version.

**Comment by kelzuriel** [comment]
I'm in the same situation, any news on this?

**Comment by benbriggs** [comment]
sorry for the wait - i'll try to get https://github.com/HubSpot/draft-convert/pull/213 published early next week

**Comment by benbriggs** [comment]
published as 2.1.13
