### ISSUE TITLE
Lists (ul and ol) are broken

### ISSUE THREAD

**Issue by stevensacks** [HubSpot/draft-convert#35]
```
Invariant Violation: convertToHTML: received block information without either a ReactElement or an object with start/end tags
at invariant (/project/node_modules/invariant/invariant.js:42:15)
    at getNestedBlockTags (/project/node_modules/draft-convert/lib/util/getNestedBlockTags.js:37:27)
    at /project/node_modules/draft-convert/lib/convertToHTML.js:111:64
 at Array.map (native)
    at /project/node_modules/draft-convert/lib/convertToHTML.js:83:34
```

This happens whenever there's an ordered or unordered list. Adding the block types to the blockToHTML function has no effect. It still throws that error.

**Comment by stevensacks** [comment]
Here's the raw object from draftjs.

```
{
    "entityMap": {},
    "blocks": [{
        "key": "9elus",
        "text": "Ordered list test",
        "type": "unstyled",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }, {
        "key": "1rd6b",
        "text": "first item",
        "type": "ordered-list-item",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }, {
        "key": "9l80r",
        "text": "second item",
        "type": "ordered-list-item",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }, {
        "key": "cr9vv",
        "text": "third item",
        "type": "ordered-list-item",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }, {
        "key": "cc2j0",
        "text": "",
        "type": "unstyled",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }]
}
```

**Comment by stevensacks** [comment]
It looks like DraftJS doesn't export the `<ol>` or `<ul>` tags that open/close the line items.

**Comment by benbriggs** [comment]
hmm, what version of `draft-convert` are you using? are you running `convertToHTML` with any configuration options passed to it? I was able to successfully convert that raw state with the default options.

**Comment by stevensacks** [comment]
We just updated to 1.3.3 and now we get this error:

```convertToHTML: received block information without either a ReactElement or an object with start/end tags```

**Comment by benbriggs** [comment]
Interesting. I still can't reproduce on 1.3.3 with the default settings so it sounds like draft-convert disagrees with your setting of the `blockToHTML` option. Is it possible that for list items you're returning HTML information that doesn't include any of these properties:

a) a `nest` property with a value of a `ReactElement`
b) a `nestStart` and `nestEnd` with string values for the html tags

If you're interested [this](https://github.com/HubSpot/draft-convert/blob/master/src/util/getNestedBlockTags.js) is likely the source of the error check. In order to know what tag (`ul` or `ol`) in this case to use to wrap blocks that require nesting. The [default block HTML](https://github.com/HubSpot/draft-convert/blob/master/src/default/defaultBlockHTML.js#L13-L20) has this definition so it sounds like it's being overridden somewhere in your configuration.

**Comment by stevensacks** [comment]
We are using your recommended example to me from awhile back:

```
const draftConverter = convertToHTML({
  blockToHTML: (block) => {
    if(block.type === 'header-two'){
      return {
        start: '<h2 class="title">',
        end: '</h2>'
      }
    }
    if(block.type === 'header-three'){
      return {
        start: '<h3 class="subtitle">',
        end: '</h3>'
      }
    }
    if (block.type === 'atomic') {
      return {
        start: '',
        end: ''
      }
    } else {
      return {
        start: '<p>',
        end: '</p>'
      }
    }
  },
  entityToHTML: (entity, originalText) => {
    const src = entity.data.src;
    if (entity.type === 'image') return `<div class="content-image">${originalText}<img src="${src}"/></div>`;
    else if (entity.type === '#mention') return parsers.games.hearthstone(entity);
    else return originalText;
  }
});
```

**Comment by stevensacks** [comment]
I tried adding this but no change:

```
    if(block.type === 'unordered-list-item'){
        return {
            element: '<li/>',
            nest: '<ul>'
        }
    }
    if(block.type === 'ordered-list-item'){
        return {
            element: '<li/>',
            nest: '<ol>'
        }
    }
```

**Comment by stevensacks** [comment]
We got it working. Thanks!

**Comment by benbriggs** [comment]
Great! Looks like that `else` at the end was clobbering it. I'd recommend avoiding one so that it can fall back to the built-in values.

**Comment by coniel** [comment]
I just ran into this issue as well. This is what fixed it for me in case anyone else is stuck on the same problem (note the nestStart/nestEnd tags):
```
if (type === 'unordered-list-item') {
  return {
    start: '<li>',
    end: '</li>',
    nestStart: '<ul>',
    nestEnd: '</ul>',
  };
}
if (type === 'ordered-list-item') {
  return {
    start: '<li>',
    end: '</li>',
    nestStart: '<ol>',
    nestEnd: '</ol>',
  };
}
```

**Comment by ddelrio1986** [comment]
@benbriggs I had to add the same thing as @coniel above. Is this a bug in draft-convert? I can share any information on my setup if needed.
