### ISSUE TITLE
Can't convert entities from and then to HTML

### ISSUE THREAD

**Issue by gdehmlow** [HubSpot/draft-convert#4]
So I'm saving these `variable` entities in my HTML.

I initially load the HTML into my editor using `convertFromHTML`, where I use `htmlToEntity` to convert that HTML entity into an actual entity by calling `Entity.create()`, and then I return that as indicated by the docs.

Now my HTML is loaded into the editor with the entities as desired. But when I go to `convertToHTML` on this exact same content state, I get this error:

> `Invariant Violation: Unknown DraftEntity key.`

I put a breakpoint there and the `instances` variable is empty.. when it should be full of the entities I imported earlier. What gives?

Unless I'm misinterpreting this, I think it's because your package has its own version of Draft, and Entities are part of the global state within Draft. When loading, I was using *my version* of Draft, so my Entities are in my global state, but not yours. This doesn't show up in tests because your tests are using the same version of Draft in and out.

This won't be an issue once [this](https://github.com/facebook/draft-js/issues/185) is resolved.

### Solution

The simplest solution I can think of is to allow me to pass in `convertToRaw`, so that your package uses my global Draft state instead of yours. What do you think?

**Comment by gdehmlow** [comment]
I think there will also be a similar problem here: https://github.com/HubSpot/draft-convert/blob/ca47c0562aa0c4203778da0d585687f41a350312/src/convertFromHTML.js#L381

**Comment by gdehmlow** [comment]
And here's a rough draft (ha): https://github.com/HubSpot/draft-convert/pull/5

**Comment by benbriggs** [comment]
Interesting...there shouldn't be another copy of Draft floating around since it's declared as an external. To confirm, in `htmlToEntity` you're returning the return value of `Entity.create` (the string key), not the `Entity` instance itself? If so, could you provide a test that runs into this issue and fails on the current version that will pass with your PR? Though it might be hard to repro the issue in a test if the problem is using it in another project.

 Completely agreed that having entity data in content state will solve a lot of problems!

**Comment by gdehmlow** [comment]
Yep I'm returning the string.

I didn't check the webpack config.. it does appear to be external. However, in my compiled `vendor.js`, I definitely have two copies of `DraftEntity`, and when I'm converting the HTML to Draft, it's using one of them to `add` and `get` entities from the map, and then when I'm converting the draft to HTML, it's using the other get.

This may then be a problem with my webpack. I'll look into it some more.

> Though it might be hard to repro the issue in a test if the problem is using it in another project.

**Comment by gdehmlow** [comment]
Okay I managed to resolve this specific issue by bumping the draft-js version of draft-convert from `0.6.0` to `0.7.0`, which is the version I'm using in my project.

**Comment by benbriggs** [comment]
Weird! I should stay up to date with the current version anyways so I'll put up a patch with the correct Draft version.

**Comment by gdehmlow** [comment]
Thank you! But yeah, really strange. I don't know enough about webpack to understand why this would happen, and it's not clear to me if it's a problem on my end or if this is the way externals work
