### ISSUE TITLE
Support for mapping br tags to paragraph blocks

### ISSUE THREAD

**Issue by adamjace** [HubSpot/draft-convert#52]
Perhaps there is already built in logic for this, but I'm not able to map <br> tags to paragraph blocks when using the `htmlToBlock` function in `convertFromHTML`

These tags are not being parsed as nodes so wondering if there is a way to achieve this?

**Comment by benbriggs** [comment]
Hmm, that should be supported - see [this test](https://github.com/HubSpot/draft-convert/blob/master/test/spec/convertFromHTML.js#L237-L242) for an example. Could you send over some example input? What version of `draft-convert` are you using? Previous to 1.4.0 whitespace was handled a bit differently by default.

**Comment by adamjace** [comment]
Ah yes, I was missing the convertToHTML step - thanks! 👍 

I guess my issue now lies with DraftJS as the empty paragraphs are not being returned as new line breaks. I've read that this is by design and they are stripped out. Is there a work around this with your extension?
