### ISSUE TITLE
convertFromHTML and nested html in atomic blocks

### ISSUE THREAD

**Issue by florapdx** [HubSpot/draft-convert#55]
Hello! First, great project -- thank you for this @benbriggs etal 💯 

I'm running into an issue w/convertFromHTML where giving it an atomic block that contains a figcaption is producing some odd output.

What I'm feeding it is, essentially:
```
// outer figure is draftJS atomic wrapper, inner is React component wrapper
<figure>
  <figure>
    <img src="foo.png" />
   <figcaption>This is an image</figcaption>
  </figure>
</figure>
```

What I'm getting out is:
```
<figure>
  <figure>
    <img src="foo.png" />
   <figcaption>This is an image</figcaption>
  </figure>
  This is an image.
</figure>
```

On each successive import, it will append the "This is an image" string again, so I end up with `...</figure>This is an image.This is an image.This is an image.</figure>` after 3 imports, and so on.

Any ideas what could be going on here? It looks like [this line](https://github.com/HubSpot/draft-convert/blob/master/src/convertFromHTML.js#L391) was introduced to fix rendering of nested elements within atomic blocks, but wondering if it shouldn't ignore (inner)text? Or maybe it's something I'm doing/not doing either here or in convertToHTML?

**Comment by benbriggs** [comment]
Interesting - could you possibly send over what your `htmlToBlock` logic is? I think a good rule of thumb for converting atomic block is using the `inBlock` argument to detect if the node being inspected is already inside of another block. in most cases nodes inside of `'atomic'` blocks don't need to be detected at all so you can `return null` if that's the case.

**Comment by florapdx** [comment]
Yeah, not doing anything special, just:
```
function convertBlock(block) {
  if (block.type === 'atomic') {
    return {
      start: '<figure>',
      end: '</figure>'
    };
  }

  return null;
}
```

I'll try messing with `inBlock` and see if that helps. Thanks!

**Comment by benbriggs** [comment]
closing this for now, feel free to reopen and follow up if you run into any more trouble!

**Comment by florapdx** [comment]
Sounds good. Thanks again @benbriggs!
