### ISSUE TITLE
Ability to ignore a elements on convertFromHTML

### ISSUE THREAD

**Issue by ArnaudRinquin** [HubSpot/draft-convert#58]
Content copied from Apple Notes may contain `<style>` elements. These elements should be completely ignore but I can't find a wait to do it.

Am I missing something?

A solution to add that to the API would be to ignore the element if `htmlToBlock` returns `false`.

**Comment by ArnaudRinquin** [comment]
ping @benbriggs any though on this?

I understand you might not have time for this improvement but if you could provide some guidance I could propose a PR.

**Comment by benbriggs** [comment]
This is a great idea! And should be pretty simple to implement. I have a working change locally that I'll test a bit more then PR later today

**Comment by benbriggs** [comment]
#62

**Comment by benbriggs** [comment]
this is resolved
