### ISSUE TITLE
What's the best way to convert <hr> elements

### ISSUE THREAD

**Issue by lukephills** [HubSpot/draft-convert#69]
Currently I'm converting to HTML like this which works fine:

```
const entityToHTML = (entity, originalText) => {
    if (entity.type === BLOCK.SEPARATOR) return '<hr>';
}
```

And I convert from HTML the `hr` like this:

```
htmlToEntity: (nodeName, node) => {
    if (nodeName === 'hr') {
        return Entity.create(BLOCK.SEPARATOR, IMMUTABLE, {});
    }
}

htmlToBlock: (nodeName, node, lastList, inBlock) => {
    if (nodeName === 'hr' && inBlock !== BLOCK.ATOMIC) {
        return BLOCK.ATOMIC;
    }
}
```

Then when I convert to HTML again, I end up with a hr wrapped in an atomic block. 
I think this is because the text inside the atomic needs to be a '-' to be a`hr` but turns into 'a' when we convert from HTML. Is there a way to set the text of an atomic on when converting from HTML?

**Comment by zadzbw** [comment]
@lukephills 

```js
blockToHTML: (block) => {
  if (block.type === 'atomic') {
    return {
      start: '',
      end: '',
    };
  }
}
```
it can convert contentState to HTML, and `<hr>` is wrapped with empty tag,
are you find better way to solve this?
