### ISSUE TITLE
Overlapping styles and entities render improperly

### ISSUE THREAD

**Issue by ryanscottaudio** [HubSpot/draft-convert#76]
For an entity that overlaps with a style:
input: [Lorem ipsum dolor sit _amet_](http://test.com)_, consectetur adipiscing elit._
expected: `<a href="http://test.com">Lorem ipsum dolor sit <i>amet</i></a><i>, consectetur adipiscing elit.</i>`
actual: `<a href="http://test.c<i>om">Lorem ipsum dolor sit amet</a></i>, consectetur adipiscing elit.`

For an style that overlaps with an entity:
input: _Lorem ipsum dolor sit_ [_amet_, consectetur adipiscing elit.](http://test.com)
expected: `<i>Lorem ipsum dolor sit <a href="http://test.com">amet</a></i><a href="http://test.com">, consectetur adipiscing elit.</a>`
actual: `<a href="http://test.c<i>om">Lorem ipsum dolor sit amet</a></i>, consectetur adipiscing elit.`

Seems like this has something to do with `prefixLength` and `suffixLength` of entities not working correctly.

**Comment by adamskihood** [comment]
I also can replicate that issue? Isn't this supposed to be fixed in https://github.com/HubSpot/draft-convert/issues/46?

**Comment by adamskihood** [comment]
Nice, thanks!
