### ISSUE TITLE
Incorrect offsets in entities after emojis

### ISSUE THREAD

**Issue by santialbo** [HubSpot/draft-convert#85]
If there is an emoji (with `.length >= 2`) before an entity. The entity originalText argument in the `entityToHTML` is incorrect. Here's a breaking test:

```js
  it('handles offset of entities after an emoji', () => {
    const contentState = buildContentState([
      {
        text: '👍 Santi Albo',
        type: 'unstyled',
        depth: 0,
        entityRanges: [{
          offset: 0,
          length: 1,
          key: 0,
        }, {
          offset: 2,
          length: 10,
          key: 1,
        }],
      }
    ], {
      0: {
        type: 'emoji',
        mutability: 'IMMUTABLE',
        data: {
          emojiUnicode: '👍'
        }
      },
      1: {
        type: 'mention',
        mutability: 'SEGMENTED',
        data: {
          href: '/users/1'
        }
      }
    });

    const result = convertToHTML({
      entityToHTML(entity, originalText) {
        if (entity.type === 'emoji') {
          return entity.data.emojiUnicode;
        } else if (entity.type === 'mention') {
          return <a href={entity.data.href}>{originalText}</a> // <-- originalText here is "anti Albo"
        }
      }
    })(contentState);
    // result === '<p>👍 S<a href="/users/1">anti Albo</a></p>'
    expect(result).toBe('<p>👍 <a href="/users/1">Santi Albo</a></p>');
  });

```

**Comment by santialbo** [comment]
I haven't tried to understand the logic underneath but at [this](https://github.com/HubSpot/draft-convert/blob/1f6b78af6864b334e02fb8f07a20feecb225ace3/src/blockEntities.js#L41) point the code is calculating the length of a string using `.length` property which doesn't like emojis.

Here's a [good article](https://mathiasbynens.be/notes/javascript-unicode) describing the issue.

**Comment by benbriggs** [comment]
Good catch, yeah doing things like that `length` check seems like the culprit. There's not going to be a super simple solution for natively supporting this since both Draft and draft-convert heavily use string and substring lengths. 

Off the top of my head, any full solution is going to need to provide replacements for calculating `length` and for accessing characters in an array with the correct indices and to integrate that throughout `convertToHTML`, `blockInlineStyles`, and `blockEntities`. I've been planning a larger refactor of the project in general to support targets other than HTML anyways so maybe I could include this as an abstraction within that.

An alternative working implementation could be using entities to represent emojis (which i think both draft-js-plugins and messenger.com do).

**Comment by santialbo** [comment]
I'm not sure I understand your last paragraph @benbriggs, in the example I treated the emoji as an entity. The problem is when the entityRange of the next entity (a "mention" entity in this case) is updated with the length of the converted emoji entity.

**Comment by santialbo** [comment]
Would it be ok to add facebook/fbjs as a dependency and use [UnicodeUtils](http://github.com/facebook/fbjs/blob/master/packages/fbjs/src/unicode/UnicodeUtils.js) which is what draft-js uses to compute lengths internally (`getUTF16Length`)?

**Comment by benbriggs** [comment]
ah sorry, i saw that then forgot when writing out my comment. i think we'll want to do something that gets that `UnicodeUtils` module or something similar into draft-convert, but from the readme for that project:
> If you are consuming the code here and you are not also a Facebook project, be prepared for a bad time.

so it might be better long-term to either find another (popular) project better suited for our use or to just copy in that module 😬 

after digging in further into messenger.com's implementation, it looks like they use an entity around the actual emoji character like you are, then use CSS on the entity to replace the actual character with their own emoji set.

**Comment by benbriggs** [comment]
@santialbo I think this fix may end up being pretty straightforward, there are just a couple more spots to use the `[...string]` syntax that compiles down to `Array.from()` that was added in #13. specifically [here](https://github.com/HubSpot/draft-convert/blob/master/src/blockEntities.js#L41) with `converted` and [here](https://github.com/HubSpot/draft-convert/blob/master/src/blockInlineStyles.js#L96) with `rawBlock.text`. I was able to get your test to pass with those changes, PR incoming
