### ISSUE TITLE
Handle block metadata from draft-js@0.8

### ISSUE THREAD

**Issue by benbriggs** [HubSpot/draft-convert#9]
Allow use of block metadata when converting to or from HTML. Metadata was added in draft-js 0.8.0

**Comment by kiliwalk** [comment]
Maybe we should make draft-js peer-dependency and use more loose version limition like `"draft-js": ">=0.7.0"` ?

**Comment by benbriggs** [comment]
good idea @kiliwalk - added in https://github.com/HubSpot/draft-convert/pull/10/commits/3e90a4176e800b80c2fa55fd0962db0bf37c14c3
