### ISSUE TITLE
unable to serialize contentState returned from convertFromHTML with entity using DraftJS.convertFromRaw

### ISSUE THREAD

**Issue by CameronAckermanSEL** [HubSpot/draft-convert#99]
When attempting to generate a content state that has a link entity, convertFromHTML seems to work up until I try to serialize the contentState to JSON using DraftJS.convertToRaw.

The code I have is:

```
    const newContentState = convertFromHTML({
      htmlToEntity: (nodeName, node, createEntity) => {
        if (nodeName === 'a') {
          return createEntity(
            'LINK',
            'MUTABLE',
            { url: node.href },
          );
        }
      },
```

This works great as long as I don't try to serialize it. 

The error I get on serialization is:

```
convertFromDraftStateToRaw.js?f453:52 Uncaught TypeError: contentState.getEntity is not a function
    at eval (convertFromDraftStateToRaw.js?f453:52)
    at Array.forEach (<anonymous>)
    at Object.convertFromDraftStateToRaw [as convertToRaw] (convertFromDraftStateToRaw.js?f453:51)
    at htmlToBlock (EditDocument.jsx?1364:365)
    at genFragment (convertFromHTML.js?2ed9:372)
    at genFragment (convertFromHTML.js?2ed9:427)
    at genFragment (convertFromHTML.js?2ed9:427)
    at genFragment (convertFromHTML.js?2ed9:427)
    at genFragment (convertFromHTML.js?2ed9:427)
    at getChunkForHTML (convertFromHTML.js?2ed9:481)
```

I'm using Draft JS 0.10.1 from Megadraft, so I think there might be some sort of version incompatiblity between Draft 0.10.1 and the contentState generated by convertFromHTML. But draft-convert uses draft-js as a peer dependency so I'm a little unsure on how this could happen.

**Comment by CameronAckermanSEL** [comment]
Ah, got a work around already! If I do 
```
```

then it bypasses the error :)

**Comment by benbriggs** [comment]
It looks like you're calling `convertToRaw` from within your `htmlToBlock` option passed to draft-convert - i think that's the source of the issue and i can't think of a reason that'd be necessary. each configuration option should be able to be a pure function that doesn't access any outside data

**Comment by CameronAckermanSEL** [comment]
@benbriggs it's because I'm cursed with requirements for tables and I have to do the conversion recursively :)

Thanks for the response by the way. As an update, I discovered that I had some old dependencies that were importing older versions of Draft and that was my issue. 

It works great now!!

**Comment by benbriggs** [comment]
ahh i see, makes sense! as long as it's not the same ContentState that is being generated by that call of `convertFromHTML`. 👍  glad you found the issue
